homework 1 commit
helixandra/AlexandraMin pull request #1
Opened 2022-03-30 22:51 UTC by helixandra

2022-03-30 23:21 UTC, obitkin requested changes
Пройдитесь по всем файлам с CTRL + ALT + L

2022-03-30 23:21 UTC, obitkin commented on src/test/resources/allOperations.xml
> +
Бесполезные пустые строки. Если вы где-то и решили внести пустую строку, то делайте это одинаково для всех файлов.

2022-03-30 23:21 UTC, obitkin commented on src/test/java/hw1/AddTests.java
> +        Calculator calculator = new Calculator();
Создание калькулятора можно вынести из тестов в родительский класс с **before** методом(относится ко всем тестам)

2022-03-30 23:21 UTC, obitkin commented on src/test/java/hw1/DivideTests.java
> +    public void divisionByZeroExceptionTest() throws Exception {
`throws Exception` лучше убрать

2022-03-30 23:21 UTC, obitkin commented on src/test/java/hw1/DivideTests.java
> +    public void doBeforeTest(){
Неговорящее название метода, тот же setupCalculator подошел бы больше

2022-03-30 23:21 UTC, obitkin commented on src/test/java/hw1/DivideTests.java
> +    }
**Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.** - [Java Code Convention](https://www.oracle.com/technetwork/java/codeconventions-150003.pdf) страница 20

2022-03-30 23:21 UTC, obitkin commented on src/test/java/hw1/AddTests.java
> +    @DataProvider
Всё таки лучше в такие места добавить пустую строку

2022-03-30 23:21 UTC, obitkin commented on src/test/java/hw1/AddTests.java
> +    }
**Methods are separated by a blank line** - [Java Code Convention](https://www.oracle.com/technetwork/java/codeconventions-150003.pdf) страница 15

2022-03-31 22:29 UTC, helixandra commented
Замечания исправлены @obitkin

2022-04-02 09:22 UTC, obitkin approved these changes
Первая работа принята. Подсказка на следующий раз: чтобы запросить ревью надо нажать соответствующую кнопку в списке ревьюеров

2022-04-03 21:13 UTC, merged