homework 2 completed
helixandra/AlexandraMin pull request #2
Opened 2022-04-06 13:36 UTC by helixandra

2022-04-06 20:39 UTC, obitkin requested changes

2022-04-06 20:39 UTC, obitkin commented on src/test/java/hw2/SeleniumBaseClass.java
> +    }
Смотрите, сейчас у вас 1 тест = 1 класс. Обычно дела обстоят не так и в одном классе будет несколько связанных тестов. У вас сейчас на все тесты будет расшарен один драйвер/браузер(если вы добавите в классы ещё тестов). Что может привести к поломкам тестов. Обычно каждый новый тест использует новый браузер, за некоторым исключением. Но в общем вам лучше вынести создание браузера в BeforeMethod. А такие общие для всех тестов как инициализация пути к драйверу оставить

2022-04-06 20:39 UTC, obitkin commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +    public void ex1Test() throws UnsupportedEncodingException {
Лишнее исключение

2022-04-06 20:39 UTC, obitkin commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +        dropdownToggle.click();
Можно в одну строчку, есть локатор намного короче и проще

2022-04-06 20:39 UTC, obitkin commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +        loginButton.click();
Зачем создавать переменные, которые вы используете один раз?

2022-04-06 20:39 UTC, obitkin commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +        softAssert.assertNotEquals(checkLogoutButton.size(), 0);
Есть проверка того, что элемент отображен на странице. Она тут будет получше

2022-04-06 20:39 UTC, obitkin commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +        softAssert.assertEquals(metalsColorsItem.getText(), "METALS & COLORS");
Можно все 4 элемента найти с помощью одного локатора. Также вынестите в цикл

2022-04-06 20:39 UTC, obitkin commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +        softAssert.assertTrue(baseImage.isDisplayed());
Можно все 4 элемента найти с помощью одного локатора. Также вынестите в цикл

2022-04-06 20:39 UTC, obitkin commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +                "wish to get more…");
Зачем сравнивать каждую строку отдельно? Просто сравните список текста со страницы и список ожидаемого текста. Это будет легче поддерживать

2022-04-06 20:39 UTC, obitkin commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +        softAssert.assertNotEquals(frameButton.size(), 0);
Есть метод получше для такой проверки

2022-04-06 20:39 UTC, obitkin commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +        softAssert.assertEquals(elementsPacks.getText(), "Elements packs");
Вынесите в цикл + есть локатор для всех элементов сразу

2022-04-06 20:39 UTC, obitkin commented on src/test/java/hw2/ex2/SeleniumTestsEx2.java
> +        dropdownToggle.click();
Можно в одну строчку, есть локатор намного короче и проще

2022-04-06 20:39 UTC, obitkin commented on src/test/java/hw2/ex2/SeleniumTestsEx2.java
> +        softAssert.assertNotEquals(checkLogoutButton.size(), 0);
Лишние переменные и проверка есть получше

2022-04-06 20:39 UTC, obitkin commented on src/test/java/hw2/ex2/SeleniumTestsEx2.java
> +
А где `assertAll()`?

2022-04-06 23:51 UTC, helixandra commented on src/test/java/hw2/SeleniumBaseClass.java
> +    }
Добавлен @BeforeMethod

2022-04-06 23:52 UTC, helixandra commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +        dropdownToggle.click();
Использован локатор `"a[href='#']"`

2022-04-06 23:52 UTC, helixandra commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +        softAssert.assertNotEquals(checkLogoutButton.size(), 0);
Исправлено на проверку `isDisplayed()`

2022-04-06 23:53 UTC, helixandra commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +        softAssert.assertEquals(metalsColorsItem.getText(), "METALS & COLORS");
Использован локатор `ul[class='uui-navigation nav navbar-nav m-l8'] > li > a`, вынесено в цикл

2022-04-06 23:54 UTC, helixandra commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +        softAssert.assertTrue(baseImage.isDisplayed());
Использован локатор `div.benefit-icon`, вынесено в цикл

2022-04-06 23:55 UTC, helixandra commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +        softAssert.assertNotEquals(frameButton.size(), 0);
Исправлено на проверку `isDisplayed()`

2022-04-06 23:55 UTC, helixandra commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +                "wish to get more…");
Исправлено на проверку со списком

2022-04-06 23:56 UTC, helixandra commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +        softAssert.assertEquals(elementsPacks.getText(), "Elements packs");
Использован локатор `ul[class='sidebar-menu left'] > li > a > span`, вынесено в цикл

2022-04-06 23:57 UTC, helixandra commented on src/test/java/hw2/ex1/SeleniumTestsEx1.java
> +    public void ex1Test() throws UnsupportedEncodingException {
Исключение убрано

2022-04-10 11:03 UTC, obitkin requested changes

2022-04-10 11:03 UTC, obitkin commented on src/test/java/hw2/ex2/SeleniumTestsEx2.java
> +        driver.close();
Во-первых, тут вы не выключаете драйвер, вы просто закрываете текущую вкладку(процесс драйвера продолжит работу). Используйте другой метод. 
Во-вторых высвобождение ресурсов нужно выносить в методы с аннотацией **after**. Смотрите, если у вас тест упадет в середине, то ресурсы не будут высвобождены(в данном случае процесс драйвера продолжит работу).

2022-04-10 11:16 UTC, helixandra commented on src/test/java/hw2/ex2/SeleniumTestsEx2.java
> +        driver.close();
Добавила AfterMethod в базовый класс с использованием quit().

2022-04-10 11:32 UTC, obitkin approved these changes
Вторая работа принята

2022-04-10 11:33 UTC, merged