homework 3 completed
helixandra/AlexandraMin pull request #3
Opened 2022-04-13 21:20 UTC by helixandra

2022-04-16 12:23 UTC, obitkin requested changes
- Вынестие page object классы в пакет `pages` а элементы в пакет `elements`
- Пройдитесь по классам с Ctrl + Alt + L

2022-04-16 12:23 UTC, obitkin commented on src/test/java/hw3/DifferentElementsPage.java
> +    }
По-моему метод должен быть protected. Врядли он будет использован в тестах напрямую

2022-04-16 12:23 UTC, obitkin commented on src/test/java/hw3/TestPage.java
> +public class TestPage {
Название очень путает, непонятно что за страницу класс описывает. Наверное HomePage

2022-04-16 12:23 UTC, obitkin commented on src/test/java/hw3/SeleniumPOBaseClass.java
> +public class SeleniumPOBaseClass {
BaseTest лучше выглядит. Из вашего названия я вижу что это какой-то класс связанный с page object(а не с тестами) и причем ещё и в названии есть лишнее 'Class'

2022-04-16 12:23 UTC, obitkin commented on src/test/java/hw3/SeleniumPOBaseClass.java
> +    }
Лучше BeforeSuit. Драйвер задается один раз перед всеми тестами. Также url можно просто вынести в поле. Плюс  softAssert больше относится к тестам(лучше вообще в тесте создавать)

2022-04-16 12:23 UTC, obitkin commented on src/test/java/hw3/IframePage.java
> +    }
Не очень подход. Если вам захочется кликнуть/получить текст кнопки то вы же не будете делать ещё 2 метода. А если будете, то у вас классы разрастутся до нечитаемого вида очень быстро. Лучше просто добавить вместо этого метода геттер для элемента, и уже для него вызывать `isDisplayed()`

2022-04-16 12:23 UTC, obitkin commented on src/test/java/hw3/TestPage.java
> +    private String userFullName;
Задавать url страницы или title в page object иде хорошая(можно просто даже захардкодить). Но вот тестовые данные юзера уже точно никак не относятся к странице. Надо разделять слои страниц/тестов/данных. Поэтому лучше задавать и хранить юзера вообще в другом месте. Можно создать отдельный data класс юзера. А задавать его в before методах

2022-04-16 12:23 UTC, obitkin commented on src/test/java/hw3/TestPage.java
> +    }
Ну вот и проблема слияния слоя данных и страниц. Не получится залогинится другим юзером. Параметризируйте метод

2022-04-16 12:23 UTC, obitkin commented on src/test/java/hw3/TestPage.java
> +    }
Выносите в утильные классы такие методы

2022-04-16 12:23 UTC, obitkin commented on src/test/java/hw3/TestPage.java
> +    }
В утильный класс

2022-04-17 13:32 UTC, obitkin commented on src/test/java/hw3/IframePage.java
> +    }
Распишу подробнее: У вас есть на странице элемент кнопка - `WebElement frameButton`. С ней можно взаимодействовать различными способами в тестах: кликнуть, получить текст, проверить отображается ли кнопка на странице. 

Для этого вы добавили отдельный метод обертку `frameButtonExists()` для проверки отображения этой кнопки. Он будет работать, всё ок. Но если таких кнопок на странице будет много и взаимодействовать с ними придется различными способами вам для каждой кнопки придется создавать по 3 метода(нажатие, получение текста и аналог frameButtonExists). Это сделает page object просто огромным и вследствии нечитаемым. 


    @FindBy(id = "frame-button")
    private WebElement frameButton;

    public String getFrameButtonText() {
        return frameButton.getText();
    }

    public boolean frameButtonExists() {
        return frameButton.isDisplayed();
    }

    public void frameButtonClick() {
        frameButton.click();
    }

Тогда в тесте будет:
`softAssert.assertTrue(frame.frameButtonExists());`

Есть другой способ для взаимодействия с кнопкой: добавить геттер для поля `private WebElement frameButton;` и уже вызывая его взаимодействовать с кнопкой. Этот метод намного более гибкий и требует просто добавить поле кнопки в класс и геттер для поля. 


    @FindBy(id = "frame-button")
    private WebElement frameButton;

    public WebElement getFrameButton() {
        return frameButton;
    }

Тогда в тесте будет:
`softAssert.assertTrue(frame.getFrameButton().isDisplayed());`

Вот это от вас я жду.


Код класса можно ещё сильнее сократить если использовать аннотацию Getter из lombok
    
    @Getter
    @FindBy(id = "frame-button")
    private WebElement frameButton;

2022-04-17 13:40 UTC, helixandra commented on src/test/java/hw3/IframePage.java
> +    }
Поняла, спасибо. Я просто думала, что в тесте вообще не должно быть никаких методов, связанных с веб драйвером.

2022-04-17 17:54 UTC, helixandra commented on src/test/java/hw3/DifferentElementsPage.java
> +    }
Исправлено

2022-04-17 17:54 UTC, helixandra commented on src/test/java/hw3/TestPage.java
> +public class TestPage {
Изменено на HomePage

2022-04-17 17:55 UTC, helixandra commented on src/test/java/hw3/SeleniumPOBaseClass.java
> +public class SeleniumPOBaseClass {
Изменено на BaseTest

2022-04-17 17:55 UTC, helixandra commented on src/test/java/hw3/SeleniumPOBaseClass.java
> +    }
Исправлено

2022-04-17 17:55 UTC, helixandra commented on src/test/java/hw3/IframePage.java
> +    }
Исправлено

2022-04-17 17:56 UTC, helixandra commented on src/test/java/hw3/TestPage.java
> +    private String userFullName;
Информация о пользователе вынесена в отдельный класс, задается в before методе

2022-04-17 17:56 UTC, helixandra commented on src/test/java/hw3/TestPage.java
> +    }
Исправлено, в метод передается информация о пользователе

2022-04-17 17:57 UTC, helixandra commented on src/test/java/hw3/TestPage.java
> +    }
Вынесено в класс PageObjectUtility

2022-04-17 17:57 UTC, helixandra commented on src/test/java/hw3/TestPage.java
> +    }
Вынесено в класс PageObjectUtility

2022-04-17 20:23 UTC, obitkin requested changes

2022-04-17 20:23 UTC, obitkin commented on src/test/java/hw3/ex1/SeleniumPageObjEx1.java
> +
Из-за этого проект не собирается

2022-04-17 20:23 UTC, obitkin commented on src/test/java/hw3/pageObject/elements/HeaderMenu.java
> +    @FindBy(css = "ul[class='uui-navigation nav navbar-nav m-l8'] > li > a")
Это плохой локатор. Цель в том, чтобы делать локаторы устойчивыми. Мы тут цепляемся за классы(можно за кучу других вещей, но тут именно так вы решили). Если хотя бы один из этих классов поменяется, то ваш локатор сразу ничего не найдет. Но если вы будете проверять не на эквивалетность, а на вхождение определенного класса, который будет при этом всегда в этом элементе, то такой локатор будет устойчивым. Тут сложно сказать какой класс является устойчивым, а какой нет. Обычно это зависит от фронта и его реализации. Но например `m-l8` не выглядит как что-то логическое, что не поменяется. Закрепится к одному классу `uui-navigation` будет лучше. 

В качестве [примера](https://material.angular.io/components/slide-toggle/overview) тут можно зацепится за класс `mat-slide-toggle`, а можно за `mat-slide-toggle mat-accent`, но если состояние тогла изменится, то поменяются классы и локатор по `mat-slide-toggle mat-accent` ничего не найдет. А локатор по вхождению `mat-slide-toggle` будет продолжать работать.

Итог:

- Большой список условий в локаторе(классов в нашем случае) ведут к более сложной поддержке локатора(достаточно поменяться одному классу и всё сломается)
- Лучше цеплятся за логику элемента(если ищем тогл, то класс `mat-slide-toggle` похож на то, что будет у всех тогл элементов, если ищем туллбар(навигационную панель), то `uui-navigation` выглядит как то, что будет у навигационной панели где бы она ни была)

2022-04-17 20:23 UTC, obitkin commented on src/test/java/hw3/pageObject/pages/HomePage.java
> +    @FindBy(css = "ul[class='uui-navigation nav navbar-nav m-l8'] > li > a")
Тут тоже надо поменять локатор

2022-04-17 20:23 UTC, obitkin commented on src/test/java/hw3/pageObject/pages/HomePage.java
> +    private List<WebElement> leftMenuItems;
Можно спокойно сократить локатор до `ul.sidebar-menu.left > li`. Слишком большая зависимость от уровня элементов, локатор становится похожим на абсолютный с соответствующими проблемами.

2022-04-18 17:12 UTC, helixandra commented on src/test/java/hw3/ex1/SeleniumPageObjEx1.java
> +
Исправлено

2022-04-18 17:23 UTC, helixandra commented on src/test/java/hw3/pageObject/elements/HeaderMenu.java
> +    @FindBy(css = "ul[class='uui-navigation nav navbar-nav m-l8'] > li > a")
Сделала такой `ul[class^='uui-navigation nav '] > li > a`, потому что если искать по вхождению класса `uui-navigation`,  в список попадает еще и меню, которое справа (с помощью которого открывается форма для логина), у верхнего меню и этого меню справа почти одинаковый набор классов и одинаковая структура, поэтому здесь `ul[class^='uui-navigation nav '] > li > a` используется именно то, что атрибут class начинается со значения `'uui-navigation nav '`.

2022-04-18 17:23 UTC, helixandra commented on src/test/java/hw3/pageObject/pages/HomePage.java
> +    @FindBy(css = "ul[class='uui-navigation nav navbar-nav m-l8'] > li > a")
Это лишнее, удалила, потому что работа с меню в классе HeaderMeu.

2022-04-19 18:03 UTC, obitkin approved these changes
Третья работа принята

2022-04-19 19:24 UTC, merged