Homework 4
helixandra/AlexandraMin pull request #4
Opened 2022-04-19 23:52 UTC by helixandra

Обзор работы Jenkins и составления Allure report:
 https://disk.yandex.ru/i/J0UPdC3raY1NXg

2022-04-22 10:55 UTC, obitkin requested changes
Одно небольшое замечание нужно исправить

2022-04-22 10:55 UTC, obitkin commented on src/test/java/hw4/BaseTest.java
> +    }
А почему нет BeforeSuit? В [документации](https://bonigarcia.dev/webdrivermanager/) указано:

_WebDriverManager in the setup method for all tests (@BeforeAll). This way, the required driver (chromedriver) will be available for all the WebDriver tests using Chrome in this class._

Вы каким-то образом разные задаете для каждого класса и поэтому используете BeforeClass? Обычно один браузер используется для всех тестов

2022-04-25 17:07 UTC, helixandra commented on src/test/java/hw4/BaseTest.java
> +    }
Исправлено на BeforeSuite

2022-04-26 11:50 UTC, obitkin approved these changes
Четвертая работа принята

2022-04-26 15:33 UTC, merged